services:
  demo:
  tms:
    # needs no arguments
  wms:
    srs: ['EPSG:4326', 'EPSG:900913', 'EPSG:3857', 'EPSG:28992']
    md:
      # metadata used in capabilities documents
      title: MapProxy Amsterdam
      abstract: MapProxy configuratie voor Amsterdam
      online_resource: http://mapproxy.org/
      contact:
        person: Stephan Zaat
        position: n/a
        organization: Gemeente Amsterdam
        address: n/a
        city: Amsterdam
        postcode: n/a
        country: Netherlands
        phone: n/a
        fax: n/a
        email: info@zosc.nl
      fees: 'None'

layers:
  - name: topo_RD
    title: Topo RD
    sources: [topo_rd_cache]
#  - name: topo_3857
#    title: Topo 3857
#    sources: [topo_3857_cache]
  name: lki_kot_RD
  title: LKI Kadastrale Objecten RD
  sources: [lki_kot_rd_cache]

caches:
  topo_rd_cache:
    grids: [nl_grid]
    sources: [topo_wms]
    cache:
      type: file
      directory_layout: tms
#  topo_3857_cache:
#    grids: [GLOBAL_WEBMERCATOR]
#    sources: [topo_wms]
#    cache:
#      type: file
#      directory_layout: tms

  lki_kot_rd_cache:
    grids: [nl_grid]
    sources: [lki_kot_wms]
    max_scale: 2500
    min_scale: 100
    cache:
      type: file
      directory_layout: tms

sources:
  topo_wms:
    type: wms
    req:
      url: http://www.diva.amsterdam.nl/cgi-bin/topografie
      layers: topovlakken,topolijnen,topoteksten
  lki_kot_wms:
    type: wms
    req:
      url: vps06.datalabamsterdam.nl/cgi-bin/mapserv?map=/srv/mapserver/lki.map
      layers: kadastraal_object

grids:
  nl_grid:
    srs: EPSG:28992
    tile_size: [256,256]
    res: [3440.64,1720.32,860.16,430.08,215.04,107.52,53.76,26.88,13.44,6.72,3.36,1.68,0.84,0.42,0.21,0.105,0.0575]
    bbox: [-285401.920,22598.080,595401.9199999999,903401.9199999999]
#    origin: ul

globals:
  cache:
    base_dir: './cache_data'
    lock_dir: './cache_data/locks'
    meta_size: [4, 4]
    meta_buffer: 128


  image:
      resampling_method: bicubic

